version: '3.2'

services: 
  db:
    image: postgres:latest
    container_name: postDB
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DATABASE: my_database
      PORT: 3000
      MODE: DEV
      # RUN_MIGRATIONS: true

  nestjs:
    depends_on: 
      - db
    image: nest-app:latest
    container_name: container-nest-app
    ports: 
      - "3000:3000"
    # restart: always
    environment: 
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DATABASE: my_database
      PORT: 3000
      MODE: DEV
      RUN_MIGRATIONS: 1

