version: '3.2'

services: 
  db:
    container_name: db
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: my_database
    networks: 
      - webnet
  web:

    image: nest-app

    container_name: web

    depends_on: 
      - db
    ports: 
      - "3000:3000"

    networks: 
      - webnet

    restart: always

networks: 
  webnet: